### PR TITLE
grantwilkins/FedSZ

### PR DESCRIPTION
**Pull request by grantwilkins**
For our study on using lossy compression to reduce communication overhead for federated learning, we implement the following changes.

### CODE REVIEW

**Comment by Zilinghan** [comment]
@grantwilkins Thanks a lot for the PR, I will review it soon

**Comment by kibaekkim** [comment]
@grantwilkins @Zilinghan can we resolve this PR and try to merge?

**Comment by Zilinghan** [comment]
> @grantwilkins @Zilinghan can we resolve this PR and try to merge?

Sorry for the delay, working on the review and merging now

**Comment by grantwilkins** [comment]
Thanks so much for the work on bringing this up to prod. Let me know if we can close this.

**Comment by Zilinghan** [comment]
@grantwilkins Hi Grant, thanks for the PR, I have the following two minor questions before closing it
- As SZx is not open-source, could you please provide a contact if a user would like to use it
- Did you use any plug-in for formatting the code, as I saw there are many lines of changes about the code format (newlines, spaces, etc.), could you recommend that formatter so that we can reformat other files as well.

**Review by Zilinghan — APPROVED** [review]

**Comment by kibaekkim** [comment]
> * Did you use any plug-in for formatting the code, as I saw there are many lines of changes about the code format (newlines, spaces, etc.), could you recommend that formatter so that we can reformat other files as well.

@Zilinghan Thanks for reviewing and addressing the issues. Regarding the formatter, we can use black, which seems popular. See [this](https://py-vscode.readthedocs.io/en/latest/files/linting.html#:~:text=Black%20is%20known%20as%20the,code%20should%20look%20and%20feel.). I am open to other options.

**Comment by grantwilkins** [comment]
Yes, I used Black as the formatter. Sorry if that forces you all to use it, but I have seen it as pretty standard. 

As for the SZx code it's a bit of a story, but you can list Sheng Di (sdi1@anl.gov) as the contact in the INSTALL for now.

Excited to merge this. We definitely will be doing a follow-up where we configure LibPressio into this to make the compressor selection and customization easier.

**Pull request merged**
