### PR TITLE
Blakely updates

### PR DESCRIPTION
**Pull request by bblakely-anl**
Fixed all relative imports, updated/streamlined .gitignore and requirements.txt, ran black to bring all files inline with normal style conventions, added an example GRPC client/server that doesn't require MPI.

### CODE REVIEW

**Comment by kibaekkim** [comment]
I feel like this needs to be reviewed by @hthieu166 @madduri.

**Review by hthieu166 — COMMENTED** [review]
Thanks for the updates! In #100. They look good to me. Only a small comment on file `src/appfl/algorithm/funcx_client_optimizer.py` , I think the `client_validation` function (line 36-79) should not be removed.

**Comment by bblakely-anl** [comment]
> Thanks for the updates! In #100. They look good to me. Only a small comment on file `src/appfl/algorithm/funcx_client_optimizer.py` , I think the `client_validation` function (line 36-79) should not be removed.

Agreed, not sure what happened there. I'll push this back (looks like my local IDE has it as a diff still).

**Comment by bblakely-anl** [comment]
> > Thanks for the updates! In #100. They look good to me. Only a small comment on file `src/appfl/algorithm/funcx_client_optimizer.py` , I think the `client_validation` function (line 36-79) should not be removed.
> 
> Agreed, not sure what happened there. I'll push this back (looks like my local IDE has it as a diff still).

Fixed!

**Comment by hthieu166** [comment]
Just merged the PR. Thank @kibaekkim and @bblakely-anl.

**Pull request merged**
